name: hungarian_hardstyle_app
description: "Hungarian Hardstyle mobile application"

publish_to: 'none'

version: 0.4.0+5

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  dio: ^5.9.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.2
  html: ^0.15.6
  flutter_html: ^3.0.0
  url_launcher: ^6.3.2

  # Spotify Player
  webview_flutter: ^4.13.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
